"""Add dip_buy fields

Revision ID: fa725c899eb4
Revises: 
Create Date: 2025-03-15 15:38:04.292018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa725c899eb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('dip_buy', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('is_dip_buy_hit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'is_dip_buy_hit')
    op.drop_column('alerts', 'dip_buy')
    # ### end Alembic commands ###
